export const screenNames = {
  HOME: 'home',
  SPLASH: 'splash',
  LOGIN: 'login',
  FORGOT: 'forgot',
  RESET: 'reset',
  CART: 'cart',
  NOTIFICATION: 'notification',
  SECHDULE: 'sechdule',
  ONBOARDING: 'Onboarding',
  MENU: 'menu',
  MENU1: 'menu1',
  ACCOUNT: 'account',
  FAVORITE: 'favorite',
  BOTTOM_TAB: 'bottomTab',
  DETAILS: 'details',
  APISCREEN: 'apiScreen',
  ADD_WATER_SOURCE: 'addWaterSource',
  DETAILS_SCREEN: 'detailScreen',
  WATER_SOURCE_SCREEN: 'waterSourceScreen',
  SEARCH_SCREEN: 'searchScreen',
  // STACKSCREEN: 'stackScreen',
  SHOP: 'shop',
  Remainder: 'remainder',
  DRAWER_TAB: 'drawerTab',
  Bottom_Tab_Connect: 'connect',
  CONNECTt_Nav: 'connectNav',
  BOTTOM_TAB_CONNECT: 'bottomTabConnect',
  PRODUCT_DETAILS: 'Details',
  AQUA_LAB_SYSTEAM: 'Aqua-Lab System',
};
