export default {
  screenTitle: 'Water Source Confi...',
  defaultSubtitle: 'PBA1', // fix krna Bhulna mt
  searchPlaceholder: 'Search',
  searchSitePlaceholder: 'Search Site Name',
  sourcesLabel: 'Sources',
  costLabel: 'Cost (Per Gallon)',
  addedOnLabel: 'Added On',
  deleteConfirmTitle: 'Confirm Delete',
  deleteConfirmMessage: 'Are you sure you want to delete this water source?',
  deleteConfirmOk: 'OK',
  deleteConfirmCancel: 'Cancel',
  errorInvalidType: 'Invalid water type selected.',
  updateFailedTitle: 'Update failed',
  updateFailedMessage: 'Bad Request (400)',
  generalError: 'Something went wrong',
  fetchError: 'Failed to fetch water source data',
  deleteError: 'Failed to delete water source',
  noDataMessage: 'No Water Sources Found',
  sitesModalTitle: 'Sites',
  sitesModalSubtitle: 'Select From 45 Sites',
  modalTitle: 'Select Water Type',
  closeButtonAlt: 'Close Modal',
  addWaterSourceTitle: 'Add Water Source',
  defaultSubtitle: 'PBA1',
  selectWaterTypeTitle: 'Select Water Type',
  selectWaterTypeMessage: 'Please choose a water type first.',
  enterCostTitle: 'Enter Cost',
  enterCostMessage: 'Please enter water cost.',
  invalidCostTitle: 'Invalid Cost',
  invalidCostMessage: 'Please enter a valid number (e.g., 10 or 10.50).',
  saveFailedTitle: 'Save failed',
  saveFailedMessage: 'Unable to save water source',
  errorTitle: 'Error',
  errorMessage: 'Failed to save',
  fetchError: 'Failed to fetch data',
  noWaterTypeTitle: 'No Water Types Found',
  noWaterTypeMessage: 'Please try again later or refresh the page.',
  searchWaterTypePlaceholder: 'Search Water Type',
  selectWaterTypeLabel: 'Select Water Type',
  waterCostPlaceholder: 'Water Cost',
  perGallon: 'per gallon',
  saveButtonText: 'Save',
  siteOne: 'Papa Bear Anderson 1 (PBA1)',
  siteTwo: 'Papa Bear Anderson 2 (PBA2)',
  siteThree: 'A2 Car Wash',
  //forget Password Screen
  forgotPasswordTitle: 'Forgot Password?',
  forgotPasswordSubtitle:
    'No worries! Enter your account email below to receive a password reset link',
  emailLabel: 'Email Address',
  emailPlaceholder: 'Email Address',
  verifyButton: 'Verify',
  errorTitle: 'Error',
  invalidEmailMessage: 'Please enter a valid email',
  userNotFoundMessage: 'This User is not in the List',
  linkSentTitle: 'Link Sent to your email',
  linkSentDescription: 'A Password reset link has been Sent to',
  loginButton: 'Login',
  resetScreen: 'reset',
  // Reset Password Screen
  resetPasswordTitle: 'Reset Password',
  resetPasswordSubtitle:
    'Enter your new password below to complete the reset process.',
  newPasswordLabel: 'New Password',
  newPasswordPlaceholder: 'New Password',
  confirmPasswordLabel: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm Password',
  invalidPasswordTitle: 'Invalid Password',
  invalidPasswordMessage: 'Please meet all the password requirements.',
  passwordMismatchTitle: 'Mismatch',
  passwordMismatchMessage: 'Password and Confirm Password must be the same.',
  passwordUpdateSuccessTitle: 'Success',
  passwordUpdateSuccessMessage: 'Password updated successfully!',
  loginScreen: 'Login',
  conditionMinLength: '8 characters or above',
  conditionSpecialChar: '1 or more special characters',
  conditionNumber: '1 or more numbers',
  conditionUpperLower: 'Upper and lowercase',
  updateButton: 'Update',
  backButton: 'Back',
  // Login Screen
  welcomeTitle: 'Welcome!',
  welcomeSubtitle: 'Enter your credentials to access your account',
  emailLabel: 'Email Address',
  emailPlaceholder: 'Email Address',
  passwordLabel: 'Password',
  passwordPlaceholder: 'Password',
  forgotPassword: 'Forgot Password?',
  loginButton: 'Login',
  registerText: 'Register',
  noAccountText: 'Don’t have an account?',
  nowText: 'now',

  // Alerts & Errors
  errorTitle: 'Error',
  passwordTooShort: 'Password must be at least 6 characters',
  invalidCredentials: 'Invalid Credential',
  invalidEmail: 'Please enter a valid email address',
  invalidPassword: 'Please enter a valid password',
  loginSuccessTitle: 'Login Success',
  // Home Screen
  membership: 'MemberShip',
  washes: 'Washes',
  washbooks: 'Washbooks',
  giftCards: 'Gift Cards',
  selectedSite: 'Selected Site',
  siteName: 'Graphene Xtreme 1 ▾',
  addToCart: 'Add to Cart',
  goToCart: 'Go To Cart',
  searchPlaceholder: 'Search',
  memberShipFound: '12 MemberShip Found',
  // Filter Modal
  filter: 'Filter',
  price: 'Price',
  lessThanTen: 'Less Than $10',
  lessThanTwenty: 'Less Than $20',
  lessThanFifty: 'Less Than $50',
  reset: 'Reset',
  apply: 'Apply',
  // Drawer Strings
  home: 'Home',
  shop: 'Shop',
  schedule: 'Schedule',
  reminders: 'Reminders',
  myAccount: 'My Account',
  cart: 'Cart',
  notifications: 'Notifications',
  logout: 'Logout',

  // Logout Alert
  logoutTitle: 'Logout',
  logoutMessage: 'Are you sure you want logout?',
  cancel: 'Cancel',
  yes: 'Yes',
  //Search Screen String
  searchText: 'Search Name',
  // Menu Screen String
  chemiaclInventory: 'Chemical Inventory',
  waterSource: 'Water Source',
  AquaLabSystem: 'Aqua-Lab System',
  location: 'Location',
  PBA2: 'PBA2',
};
